title: How to change careeers
author: eratem
email: notpublic@hidden.com
description: > # this means to ignore newlines until "baseurl:"
  The result open attempt to learn something new and create positive change.

theme: minima

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  eratem # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
